### ISSUE TITLE
Fails when trying to prompt for username

### ISSUE THREAD

**Issue by cliff-wakefield** [argais/aws_cli_adfs#1]
```
$ python saml.py
Username (domain\username): wakefieldc
Traceback (most recent call last):
  File "saml.py", line 54, in <module>
    username = input("Username (domain\\username): ")
  File "<string>", line 1, in <module>
NameError: name 'myuserid' is not defined
```

**Comment by cliff-wakefield** [comment]
Had to change back to

```
print "Username (domain\\username): ",
username = raw_input()
```

To make it work.

**Comment by argais** [comment]
Use Python 3.5 instead of 2.7 ;) 

Fernando Battistella

**Comment by argais** [comment]
Added note on readme about requiring python 3.5.

There are other issues with unicode on python 2.7, besides the input thing. 
Unfortunately I don't have the time to track them down and fix them.
